#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "7152030076:AAHDmELD89TW6QX4zU13WmqVrG--JN9R7sU")
    API_ID = int(os.environ["API_ID", 24556410]
    API_HASH = os.environ["API_HASH", "0aa84892224ccf16597ca8d6a9375bdf"]
    AUTH_USERS = "6488911325"""
# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/Stubborn1223 ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
